[package]
name = "snowsql-derive"
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Connect to Snowflake, used with snowflake-deserializer crate. Forked from https://github.com/Ripper53/snowflake-connector"
keywords = ["snowflake", "data-science"]
categories = ["database"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "2"
quote = "1.0"
snowsql-deserialize = { path = "../snowsql-deserialize" }

